In [1]:
import numpy as np

In [2]:
a=2
b=3
c=-1
d=-0.5

In [3]:
-b//a-(-1)*c*b/d**c%c%d + (0 and 1 or not 0)

-1.0

In [4]:
a=10
b=20
c=(a if a>b else b)*2
d=list(range(10))
d[0]=c
print(d[0:6:2])

[40, 2, 4]


In [5]:
def foo(x):
    x+=1
    if x<20:
        return foo(x)+1
    else:
        return x
x=10
print(foo(x))

29


In [7]:
def change1(mylist):
    mylist[0] = 2
    print(mylist)
    return

def change2(mylist):
    mylist = [1,2,3,4]
    print(mylist)
    return

mylist = [10,20,30]
change1(mylist)
print(mylist)
change2(mylist)
print(mylist)

[2, 20, 30]
[2, 20, 30]
[1, 2, 3, 4]
[2, 20, 30]


In [9]:
x1 = np.arange(8)
print(x1)

[0 1 2 3 4 5 6 7]


In [10]:
x2 = np.reshape(x1,(2,4))
print(x2)

[[0 1 2 3]
 [4 5 6 7]]


In [11]:
print(np.roll(x2,1,axis=0))

[[4 5 6 7]
 [0 1 2 3]]


In [12]:
import random

numberOfPiles = 10
maxIter = 10000

piles = np.empty(numberOfPiles)
piles.fill(numberOfPiles)
totPiles = np.sum(piles)
numPiles = numberOfPiles
x = 0;
while (x < maxIter and piles.size > 1):
    piles = piles[np.nonzero(piles)]
    for i in np.arange(piles.size):
        piles[i] -= 1
        num = np.random.randint(piles.size)
        piles[num] += 1
    numPiles = piles.size
    x += 1


print("The number of piles remaining are: ", numPiles)

The number of piles remaining are:  1
